chore: Update 0.0.0 with sandbox changes

diff --git a/cpp/0.0.0/bin/install_dependencies b/cpp/0.0.0/bin/install_dependencies
--- a/cpp/0.0.0/bin/install_dependencies
+++ b/cpp/0.0.0/bin/install_dependencies
@@ -1,16 +1,28 @@
 #!/bin/bash
 # shellcheck disable=2016
 
-file_args="${*}"
-fmt_bold="\033[1m"
-fmt_cyan="\033[36m"
-fmt_green="\033[32m"
-fmt_red="\033[31m"
-fmt_reset="\033[0m"
-fmt_yellow="\033[33m"
+set -e
 
 function build_app_dir() {
   echo -e "$(realpath "$(dirname "${BASH_SOURCE[0]}")/../")"
+}
+
+# shellcheck disable=1090,1091
+source "$(build_app_dir)/bin/utils" # ASCII, ascii_print
+
+function exempt_service_passwords() {
+  content="%sudo ALL=(ALL) NOPASSWD: /usr/sbin/service"
+
+  if [[ -f "/etc/sudoers.d/service_no_passwd" ]]; then
+    existing_content=$(sudo cat "/etc/sudoers.d/service_no_passwd")
+
+    if ( echo "${existing_content}" | grep -q "${content}" ); then
+      return 0
+    fi
+  fi
+
+  ascii_print "📝 Editing sudoers" "yellow"
+  echo -e "${content}" | sudo tee /etc/sudoers.d/service_no_passwd > /dev/null
 }
 
 function install_apt_packages() {
@@ -33,20 +45,22 @@ function install_asdf() {
   asdf_completion_cmd='. $HOME/.asdf/completions/asdf.bash'
   asdf_source_cmd='. $HOME/.asdf/asdf.sh'
 
-  [ ! -d "$HOME/.asdf" ] && \
+  [ ! -d "${HOME}/.asdf" ] && \
     log_install_start "💻 asdf" && \
     git clone https://github.com/asdf-vm/asdf.git ~/.asdf
 
-  touch ~/.bashrc
+  bashrc_path="${HOME}/.bashrc"
 
-  bashrc_contents=$(cat ~/.bashrc)
+  touch "${bashrc_path}"
 
-  if ! (echo "$bashrc_contents" | grep -q "$asdf_source_cmd"); then
-    echo -e "\n$asdf_source_cmd" >> ~/.bashrc
+  bashrc_contents=$(cat "${bashrc_path}")
+
+  if ! (echo "${bashrc_contents}" | grep -q "${asdf_source_cmd}"); then
+    echo -e "\n${asdf_source_cmd}" >> "${bashrc_path}"
   fi
 
-  if ! (echo "$bashrc_contents" | grep -q "$asdf_completion_cmd"); then
-    echo -e "\n$asdf_completion_cmd" >> ~/.bashrc
+  if ! (echo "${bashrc_contents}" | grep -q "${asdf_completion_cmd}"); then
+    echo -e "\n${asdf_completion_cmd}" >> "${bashrc_path}"
   fi
 }
 
@@ -86,10 +100,8 @@ function install_brew_packages() {
 
   [[ "${#to_install[*]}" = "0" ]] && return 0
 
-  # log_install_start "${to_install[*]}"
-
   log_install_start "${to_install[*]}" && \
-  brew install "${to_install[@]}"
+    brew install "${to_install[@]}"
 }
 
 function install_cpp_dependencies() {
@@ -101,19 +113,50 @@ function install_cpp_dependencies() {
   install_nlohmann_json
 }
 
-function install_etrade_dependencies() {
-  install_apt_packages firefox firefox-geckodriver
+function install_language_from_asdf() {
+  asdf_bin="${HOME}/.asdf/bin/asdf"
+  language="${1}"
+  version="${2}"
 
-  if [[ "$file_args" =~ .*--server.* ]]
-  then
-    echo "installing server ruby"
-    install_ruby_from_source
-  else
-    echo "installing local"
-    install_ruby_from_asdf
+  if [[ ! -d "${HOME}/.asdf" ]]; then
+    ascii_print "❗ Install asdf before $(to_title "${language}") ${version}" "red"
+    install_asdf
   fi
 
-  install_ruby_gems bundler
+  [ ! -d "${HOME}/.asdf/plugins/${language}" ] && \
+    log_install_start "$(to_title "${language}") plugin" && \
+    "${asdf_bin}" plugin add "${language}"
+
+  [ ! -d "${HOME}/.asdf/installs/${language}/${version}" ] && \
+    log_install_start "💻 $(to_title "${language}") ${version}" && \
+    "${asdf_bin}" install "${language}" "${version}" &&
+    "${asdf_bin}" reshim "${language}"
+
+  tool_versions_path="${app_dir}/.tool-versions"
+
+  if [[ -f "${tool_versions_path}" ]]; then
+    if ! (grep -q "\b${language}\b" "${tool_versions_path}"); then
+      echo -e "${language} ${version}" >> "${tool_versions_path}"
+    fi
+  else
+    echo -e "${language} ${version}" > "${tool_versions_path}"
+  fi
+}
+
+function install_pgformatter() {
+  if [[ -n $(which pg_format) ]]; then
+    return 0
+  fi
+
+  log_install_start "🐘😍 pgFormatter"
+
+  version=5.5
+  wget https://github.com/darold/pgFormatter/archive/refs/tags/v${version}.tar.gz
+  tar xzf v${version}.tar.gz
+  cd pgFormatter-${version}/ || exit
+  perl Makefile.PL
+  make && sudo make install
+  cd ../ && \rm -rf v${version}.tar.gz && rm -rf pgFormatter-${version} #clean up
 }
 
 function install_postgresql() {
@@ -125,6 +168,8 @@ function install_postgresql() {
     fi
 
     log_install_start "🐘 PostgreSQL"
+
+    install_apt_packages "lsb-release"
 
     sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
@@ -146,99 +191,45 @@ function install_nlohmann_json() {
   'rm' -rf /tmp/nlohmann/
 }
 
-function install_ruby_from_asdf() {
-  asdf_bin="$HOME/.asdf/bin/asdf"
-  ruby_version="3.0.3"
+function install_python_dependencies() {
+  app_dir=$(build_app_dir)
+  log_install_start "🐍 Python Dependencies"
 
-  install_asdf
-
-  [ ! -d "$HOME/.asdf" ] && \
-    echo -e "${fmt_bold}${fmt_red}❌ Install asdf before ruby${fmt_reset}" &&
-    return 1
-
-  [ ! -d "$HOME/.asdf/plugins/ruby" ] && \
-    log_install_start "ruby plugin" && \
-    "$asdf_bin" plugin add ruby
-
-  [ ! -d "$HOME/.asdf/installs/ruby/$ruby_version" ] && \
-    log_install_start "💎 Ruby $ruby_version" && \
-    "$asdf_bin" install ruby "$ruby_version" &&
-    "$asdf_bin" reshim ruby
-
-  if [[ -f "$HOME/.tool-versions" ]]; then
-    if ! (grep -q "\bruby\b" "$HOME/.tool-versions"); then
-      echo -e "ruby $ruby_version" >> "$HOME/.tool-versions"
-    fi
-  else
-    echo -e "ruby $ruby_version" > "$HOME/.tool-versions"
-  fi
-}
-
-function install_ruby_from_source() {
-  [[ "$(which ruby)" != "" ]] && return 0
-
-  ruby_version="ruby-3.0.3"
-  zip_filename="$ruby_version.tar.gz"
-
-  install_apt_packages build-essential libssl-dev zlib1g-dev
-  sudo wget "https://cache.ruby-lang.org/pub/ruby/3.0/$zip_filename" -P /opt/
-
-  cd /opt/ || return 0
-  sudo tar -xzvf "$zip_filename"
-  cd "$ruby_version/" || return 0
-  sudo ./configure
-  sudo make
-  sudo make install
-  sudo 'rm' "/opt/$zip_filename"
-
-  sudo chown -R "$(whoami):$(whoami)" /usr/local/lib/ruby/
-  sudo chown -R "$(whoami):$(whoami)" /usr/local/bin/
-
-  echo -e "---\ngem: --no-document" > ~/.gemrc
-}
-
-function install_ruby_gems() {
-  to_install=()
-
-  [[ "$(which gem)" = "" ]] && return 0
-
-  for arg in "$@"; do
-    if ! (gem list | grep "$arg" | awk '{print $1}' | grep -q "^$arg$"); then
-      to_install+=("$arg")
-    fi
-  done
-
-  [[ "${#to_install[*]}" = "0" ]] && return 0
-
-  gem install "${to_install[*]}"
+  pip3 install -r "${app_dir}/deps/requirements.txt"
+  asdf reshim python
 }
 
 function log_install_start() {
-  echo -e "${fmt_bold}${fmt_yellow}📦 Installing ${fmt_reset}${fmt_cyan}$1${fmt_reset}"
+  ascii_print "📦 Installing ${ASCII["reset"]}${ASCII["cyan"]}${1}" "yellow"
 }
-
-install_postgresql
 
 if [[ $OSTYPE =~ ^linux.* ]]; then
   packages=(
-    "g++"
-    "gcc"
+    "clang-format" # C Formatting
+    "g++" # C++
+    "gcc" # C++
     "jq"
-    "libcurl4-openssl-dev"
-    "libpq-dev"
-    "libssl-dev"
-    "lsb-release"
+    "libcurl4-openssl-dev" # Curl Client
+    "libffi-dev" # Python
+    "libpq-dev" # LibPQ
     "netplan.io"
+    "openssh-server" # sshd
     "openssl"
-    "python3"
+    "shellcheck" # Shell Formatting
   )
 
   sudo apt-get update
   install_apt_packages "${packages[@]}"
 fi
 
-[[ $OSTYPE =~ ^darwin.* ]] && install_brew_packages coreutils "openssl@3" "python@3.10"
+[[ $OSTYPE =~ ^darwin.* ]] && install_brew_packages coreutils "openssl@3"
 
+install_postgresql
+install_pgformatter
+install_asdf
+install_language_from_asdf "python" "3.11.4"
 install_cpp_dependencies
+install_python_dependencies
+exempt_service_passwords
 
-echo -e "${fmt_bold}${fmt_green}🎉 Successfully installed dependencies!${fmt_reset}"
+ascii_print "🎉 Successfully installed dependencies!" "green"
